name: Build Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10, v2.1.4rc5

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Prepare Environment
        id: prepare_env
        run: |
          PROJECT="${GITHUB_REPOSITORY#ruipin/}"
          PROJECT_NO_FVTT="${PROJECT#fvtt-}"

          echo "PROJECT=${PROJECT}"                 >> $GITHUB_ENV
          echo "PROJECT_NO_FVTT=${PROJECT_NO_FVTT}" >> $GITHUB_ENV

          echo ::set-output name=PROJECT::${PROJECT}
          echo ::set-output name=PROJECT_NO_FVTT::${PROJECT_NO_FVTT}

          VERSION="${GITHUB_REF#refs/*/v}"
          SPLIT_VERSION_1="${VERSION#*.}"
          SPLIT_VERSION_2="${SPLIT_VERSION_1#*.}"
          MAJOR_VERSION="${VERSION%%.*}"
          MINOR_VERSION="${SPLIT_VERSION_1%%.*}"
          SPLIT_VERSION_3="${SPLIT_VERSION_2%%[^0-9]*}"
          PATCH_VERSION="${SPLIT_VERSION_3}"
          SUFFIX_VERSION="${SPLIT_VERSION_2#${SPLIT_VERSION_3}}"
          SUFFIX_VERSION="${SUFFIX_VERSION#.}"
          SUFFIX_VERSION="${SUFFIX_VERSION#-}"

          IS_PRERELEASE="true"
          if [[ "$SUFFIX_VERSION" != *rc* ]]; then
            git merge-base --is-ancestor HEAD origin/master && IS_PRERELEASE="false"
          fi

          echo ::set-output name=VERSION::${VERSION}
          echo ::set-output name=MAJOR_VERSION::${MAJOR_VERSION}
          echo ::set-output name=MINOR_VERSION::${MINOR_VERSION}
          echo ::set-output name=PATCH_VERSION::${PATCH_VERSION}
          echo ::set-output name=SUFFIX_VERSION::${SUFFIX_VERSION}
          echo ::set-output name=IS_PRERELEASE::${IS_PRERELEASE}

          echo "VERSION=${VERSION}"               >> $GITHUB_ENV
          echo "MAJOR_VERSION=${MAJOR_VERSION}"   >> $GITHUB_ENV
          echo "MINOR_VERSION=${MINOR_VERSION}"   >> $GITHUB_ENV
          echo "PATCH_VERSION=${PATCH_VERSION}"   >> $GITHUB_ENV
          echo "SUFFIX_VERSION=${SUFFIX_VERSION}" >> $GITHUB_ENV
          echo "IS_PRERELEASE=${IS_PRERELEASE}"   >> $GITHUB_ENV

          echo "Project: '$PROJECT' ; Version: '$VERSION' ; Major: '$MAJOR_VERSION' ; Minor: '$MINOR_VERSION' ; Patch: '$PATCH_VERSION' ; Suffix: '$SUFFIX_VERSION' ; Pre-release: '$IS_PRERELEASE' ;"

          if ! grep "\"$VERSION\"" module.json ; then
            echo "module.json version does not match the tag"
            exit 1
          fi

        shell: bash


      - name: Build
        run: |

          sed -r -i \
            -e 's~("manifest":)[^,]*~\1 "https://github.com/ruipin/${{ steps.prepare_env.outputs.PROJECT }}/releases/latest/download/module.json"~' \
            -e 's~("download":)[^,]*~\1 "https://github.com/ruipin/${{ steps.prepare_env.outputs.PROJECT }}/releases/download/v${{ steps.prepare_env.outputs.VERSION }}/${{ steps.prepare_env.outputs.PROJECT_NO_FVTT }}-v${{ steps.prepare_env.outputs.VERSION }}.zip"~' \
            module.json

          7z a -tzip "${{ steps.prepare_env.outputs.PROJECT_NO_FVTT }}-v${{ steps.prepare_env.outputs.VERSION }}.zip" * -mx0


      - name: Create/Upload Zip
        uses: ncipollo/release-action@1df3b9d90da563e0a6f5e19f350774bc1074df54
        with:
          artifacts: "./${{ steps.prepare_env.outputs.PROJECT_NO_FVTT }}-v${{ steps.prepare_env.outputs.VERSION }}.zip"
          artifactContentType: application/zip
          allowUpdates: true
          replacesArtifacts: true
          prerelease: ${{ steps.prepare_env.outputs.IS_PRERELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Upload Json
        uses: ncipollo/release-action@1df3b9d90da563e0a6f5e19f350774bc1074df54
        with:
          artifacts: ./module.json
          artifactContentType: application/json
          allowUpdates: true
          replacesArtifacts: true
          prerelease: ${{ steps.prepare_env.outputs.IS_PRERELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}